### PR TITLE
fanquake 0.12.0rc2 sigs

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by Michagogo** [comment]
Linux mismatches...

**Comment by MarcoFalke** [comment]
> Linux mismatches...

That's odd.

**Comment by laanwj** [comment]
Yes, weird. Linux is the only mismatch, and @fanquake's is the only one that mismatches:

```
MarcoFalke: OK
michagogo: OK
achow101: OK
cfields: OK
fanquake: MISMATCH
laanwj: OK
jonasschnelli: OK
prab: OK
```

Mine;

    6712e1d3d856a027fe5802ddb3d61be3f2ee86fa0e3377bfec56eda52e7c75f0  bitcoin-0.12.0-linux32.tar.gz
    4676b0e61124f2cb9df530808a00a7ce8ca1c5b2e33950a150a77d6eb735daaf  bitcoin-0.12.0-linux64.tar.gz

Fanquake's:

    71337d9295151f60b9859925fa953318efcc7a855e82ec0a561428f5f8ece46f  bitcoin-0.12.0-linux32.tar.gz
    5181e857ce293f37658e01ed0601d48f34328f5794abc2bb9ac2654e92692fbe  bitcoin-0.12.0-linux64.tar.gz

Source tarball does match.

Can you reproduce this? Do you still have the .tar.gzs for comparison?

**Comment by fanquake** [comment]
I should still have the all the files. Will make them available shortly.

**Comment by MarcoFalke** [comment]
I think you can just put them in a zip and GitHub will add them to the comment.

**Comment by laanwj** [comment]
I've looked at the executables, and they all differ. The most apparent different (and possibly the cause) when comparing (a) your output and (b) our output is this:
```
- 0x00000001 (NEEDED)                     Shared library: [librt.so.1]
```
So our executable no longer requires `librt.so.1`, but yours does.

Other differences are in the version requirements:
```
  Version: 1  File: libm.so.6  Cnt: 1
    Name: GLIBC_2.0  Flags: none  Version: 21
- Version: 1  File: librt.so.1  Cnt: 1
-   Name: GLIBC_2.2  Flags: none  Version: 16
  Version: 1  File: ld-linux.so.2  Cnt: 1
-   Name: GLIBC_2.3  Flags: none  Version: 15
+   Name: GLIBC_2.3  Flags: none  Version: 16
  Version: 1  File: libgcc_s.so.1  Cnt: 4
    Name: GCC_4.2.0  Flags: none  Version: 17
-   Name: GCC_3.3  Flags: none  Version: 14
+   Name: GCC_3.3  Flags: none  Version: 15
    Name: GLIBC_2.0  Flags: none  Version: 9
    Name: GCC_3.0  Flags: none  Version: 8
  Version: 1  File: libpthread.so.0  Cnt: 4
    Name: GLIBC_2.1  Flags: none  Version: 20
-   Name: GLIBC_2.2  Flags: none  Version: 13
+   Name: GLIBC_2.2  Flags: none  Version: 14
    Name: GLIBC_2.3.2  Flags: none  Version: 6
    Name: GLIBC_2.0  Flags: none  Version: 4
- Version: 1  File: libc.so.6  Cnt: 9
+ Version: 1  File: libc.so.6  Cnt: 10
    Name: GLIBC_2.3.3  Flags: none  Version: 19
    Name: GLIBC_2.4  Flags: none  Version: 18
-   Name: GLIBC_2.3  Flags: none  Version: 12
-   Name: GLIBC_2.7  Flags: none  Version: 11
-   Name: GLIBC_2.3.4  Flags: none  Version: 10
+   Name: GLIBC_2.3  Flags: none  Version: 13
+   Name: GLIBC_2.7  Flags: none  Version: 12
+   Name: GLIBC_2.3.4  Flags: none  Version: 11
+   Name: GLIBC_2.17  Flags: none  Version: 10
    Name: GLIBC_2.1.3  Flags: none  Version: 7
    Name: GLIBC_2.1  Flags: none  Version: 5
    Name: GLIBC_2.0  Flags: none  Version: 3
```
This points towards a major difference in the glibc version in the base image.

**Pull request merged**
