### PR TITLE
fanquake 0.12.0rc5 unsigned sigs

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by laanwj** [comment]
Your build results (the same as my former ones) are a result of a new build with a stale cache.

There has been a sudden toolchain change, see https://lists.ubuntu.com/archives/trusty-changes/2016-February/021179.html This results in slightly different executables. 

Unfortunately that means having to wipe the 0.12 caches (`cache/*-0.12`) and building again to get the same output as cfields and me.

**Comment by achow101** [comment]
Does that mean that I, @Michagogo and @PRabahy need to redo our builds with clean caches?

**Comment by MarcoFalke** [comment]
From IRC

> @wumpus: in any case: everyone should nuke cache and rebuild rc5

**Comment by PRabahy** [comment]
Nuked entire VM and am rebuilding now. (I wanted to do this anyway to get up to the latest version of debian)

**Comment by fanquake** [comment]
@laanwj Cheers for the heads up. Updated unsigned and added signed sigs.

**Pull request merged**
