### PR TITLE
My sigs for 0.10.0rc3

### PR DESCRIPTION
**Pull request by gdm85**
3rd attempt (#82, #83)

### CODE REVIEW

**Comment by Michagogo** [comment]
FYI, you don't have to close and recreate new PRs each time. You can just
repush to the branch (master, in this case) and the PR will update.

**Comment by gdm85** [comment]
@Michagogo there's a bug/feature in github that automatically closes the PR when history of the fork is rewritten and no commits are seen on top of it.

Furthermore, when you add a new commit and push it, it won't allow to re-open the PR saying that there are 0 commits ahead on that fork (which is not true).

Sorry for the noise...

**Comment by Michagogo** [comment]
Hmm? Not sure what you mean. Pretty sure I've updated PRs in the past...
Which Git operations are you performing exactly?

**Comment by gdm85** [comment]
@Michagogo I am doing it in an unusual/incorrect way, no doubt. But still...

```
git remote update
git reset --hard upstream/master
git push origin +master
```
(here the PR gets closed & screwed up)
Then I fix the commit with:
```
git add ...
git commit
git push
```

But there's at this point no way to re-open the PR :(

Probably I'd have had to skip the ``git push origin +master`` and do everything in 1 push to avoid the auto-close & glitch.

**Comment by sipa** [comment]
Yes, no need to push after the reset. Just push once your local branch
reflects what you want the PR to be.

**Comment by jonasschnelli** [comment]
i always do `git push <remote> --force` to overwrite my commit(s) in the PR.

**Comment by Michagogo** [comment]
Ah, interesting. A couple tips -- rather than `upstream/master`, you can
rewind more easily by specifying something like `HEAD~n`, to rewind
n commits. Even easier for something like this, though, and the way I do it
if it's this easy/simple: `git add <...> && git commit --amend && git push
--force`

**Comment by gdm85** [comment]
@jonasschnelli that doesn't work well if upstream rewrote the history.

Usually I just rebase the commit and push it, but when I tried this I found there were 8 extra commits in my PR (!!!). So I ended up with this more radical approach.

**Comment by gdm85** [comment]
@Michagogo doing a push --force is exactly how I found extra commits in my PR..so I wanted to replace fork's master branch with upstream/master

**Comment by Michagogo** [comment]
Hm, looks like thst didn't monospace properly... And apparent the mobile interface doesn't have an edit button.

**Comment by Michagogo** [comment]
Extra commits? How's that?

**Comment by gdm85** [comment]
@Michagogo extra commits that had been merged/edit/moved around (they were definitively from gitian.sigs repo, but other authors - not me). I am not a git expert but I think this is what you see when history has been changed?

**Comment by jonasschnelli** [comment]
@gdm85 
When i mess up thing, i do...
1. create a new local branch from current master (master should be up to date, to a `git pull` in master before)
2. cherry pick your commit(s) from the messed up local branch
3. `git push <remote> <localbranch>:<remotebranch> --force`

Never had problems.

**Comment by Michagogo** [comment]
You also don't need to be based on current master for something like this
where you're just adding files.

**Comment by laanwj** [comment]
Github closes a pull request if the underlying commit is either merged, or the branch is removed.

If you close the pull manually then - while the pull is closed - force-push new commits, you can't reopen it again.

I've never had an issue closing on me when force-pushing to the pull's branch.

**Comment by Michagogo** [comment]
I guess if you revert to the base commit and force-push before adding the
new commit, it might treat it as if it were merged?

**Comment by gdm85** [comment]
It's fairly reproducible with the steps in [this comment](https://github.com/bitcoin/gitian.sigs/pull/84#issuecomment-70058933)

**Pull request merged**
