### PR TITLE
michagogo's gitian sigs for 0.12.1rc1

### PR DESCRIPTION
**Pull request by Michagogo**

### CODE REVIEW

**Comment by shangzhou** [comment]
not rc2 ?

**Comment by btcdrak** [comment]
No point building rc1, it was killed yesterday pending 7835

**Comment by Michagogo** [comment]
Ah, I must have missed that. Anyway, now I have the deps at least…

**Comment by theuni** [comment]
Closing in favor of rc2.

**Comment by Michagogo** [comment]
Uh, they're both there. That's what happens when I run my script when
there's still a PR outstanding…

**Comment by MarcoFalke** [comment]
@Michagogo Just squash the commits and open a new pull

**Comment by Michagogo** [comment]
I will at some point if nobody pulls my sigs, but it may be a few days
before I get around to being at my computer.

**Comment by theuni** [comment]
Sorry, I didn't notice that it was updated. 
I cherry-picked the rc2 sigs commit.

**Pull request closed without merging**
