### PR TITLE
gdm85 0.10.0rc1 signatures

### PR DESCRIPTION
**Pull request by gdm85**
My sigs, automatically built with docker + gitian-builder + vmbuilder (https://github.com/gdm85/tenku/tree/master/docker/gitian-bitcoin-host)

### CODE REVIEW

**Comment by laanwj** [comment]
Thanks!
Are these meant to be only linux sigs?

**Comment by gdm85** [comment]
it's a pleasure :)

@laanwj yes they are Linux-only, 32bit and 64bit

**Comment by Michagogo** [comment]
Just out of curiosity, how come?

**Comment by gdm85** [comment]
@Michagogo you mean why I didn't make signatures for Windows and Mac?

It's because I further automated the full process (and made it reproducible with the linked scripts/tools), and focused only on Linux (that is selfishly what I/we use).

But I see that since the introduction of depends cache I could just enable it for other OSes; in the past I didn't want to bother at maintaining a list of input source URLs for other OSes too. Will give it a try, maybe for next rc or release.

**Comment by Michagogo** [comment]
Are you modifying the descriptors at all? Because if not, I would think it
would just be 2 more gbuild/gsign pairs. (And a bunch more time)

**Comment by gdm85** [comment]
@Michagogo not at all, so yes it's just 2 more gbuilds (which I would want to run in parallel too) and gsigns as you said

**Pull request merged**
