### PR TITLE
fivepice's 0.16.0rc4 sigs

### PR DESCRIPTION
**Pull request by fivepiece**

### CODE REVIEW

**Comment by NeedsAdjustment** [comment]
Please edit the title and commit message of your request to remove any typos that may have occurred.

**Comment by fivepiece** [comment]
This is verbatim the same title as I had on #661 with `s/3/4` .
Let me know what needs to be changed..

**Comment by MeshCollider** [comment]
@fivepiece ignore them, they are just making a joke about how you misspelt your name in the title
@NeedsAdjustment doesn't matter if there is a typo...

**Comment by NeedsAdjustment** [comment]
@MeshCollider please don't tell me I don't matter :(

**Comment by fivepiece** [comment]
hehe :)
That's what I get for copypasting.

**Pull request merged**
