### PR TITLE
michagogo's gitian sigs for 0.12.0rc5

### PR DESCRIPTION
**Pull request by Michagogo**

### CODE REVIEW

**Comment by fanquake** [comment]
Why have a commit to remove the incorrect sigs? Can't you just add the new ones?

**Comment by Michagogo** [comment]
Maybe. I have a script that automates the build process (including pulling
(upstream and origin), committing, pushing, PRing using the GH API...) and
I don't know how gsign works if the sigs already exist. If it overwrites,
great, but I don't actually know how that works. And I don't know enough
about git to know how the checkout/pull commands would handle files that
were deleted/changed. Yes, I could have researched those and it's quite
possible I could have just done it all with no problem, but at the time I
was kinda in a hurry, so I just went with what I knew was safe and would
just work.

**Comment by laanwj** [comment]
You could squash these commits and have the same end result.
But it's the end result that matters here so no need to bother.

**Comment by Michagogo** [comment]
Yeah, I'd have squashed if I could, but I haven't gotten to my computer
since kicking off the build script.

**Pull request merged**
