### PR TITLE
replace fivepiece 0.16.0 signatures with detached sigs

### PR DESCRIPTION
**Pull request by fivepiece**
fixup : re-sign non-codesigned 0.16.0 descriptors with detached sigs

### CODE REVIEW

**Comment by fivepiece** [comment]
I see travis is angry because I removed (my) files.  Let me know if I should include that in a separate commit or if's more sensible to just close this PR :)

**Comment by MeshCollider** [comment]
@fivepiece the travis warning isn't a worry, it just shows its doing its job in detecting such things :)

**Comment by fanquake** [comment]
I’m not sure we want to modify files that have been committed.

**Comment by fivepiece** [comment]
Alright, closing this.  Shouldn't be a problem to reopen if the need arises.

**Pull request closed without merging**
