### PR TITLE
jonatack 0.19.1rc2 unsigned sigs

### PR DESCRIPTION
**Pull request by jonatack**

### CODE REVIEW

**Comment by jonatack** [comment]
Will try building unsigned sigs for Win and/or macOS and rebase onto this commit.

**Comment by MarcoFalke** [comment]
Windows should work just fine, but for macOS you need the SDK https://github.com/bitcoin/bitcoin/pull/16392#issuecomment-581593272

**Comment by jonatack** [comment]
Win now built. Thanks! Just now came across `gitian-builder/inputs/MacOSX10.11.sdk.tar.gz: no such file or directory` and will check out your link.

**Comment by jonatack** [comment]
Thanks!

Keys here, if useful: https://keybase.io/jonatack

**Pull request merged**
