### PR TITLE
Add v0.13.0rc1 signed binary sigs for achow101

### PR DESCRIPTION
**Pull request by achow101**

### CODE REVIEW

**Comment by theuni** [comment]
Thanks! Dirname is busted though. v0.13.0rc1-[osx|win]-signed should be 0.13.0rc1-[osx|win]-signed.

I can't remember if that requires re-signing or not.

**Comment by achow101** [comment]
Fixed.

I don't think it needs to be resigned.

**Comment by Michagogo** [comment]
They do need to be resigned. The release string is contained in the body of
the file, at the bottom.

**Comment by laanwj** [comment]
yeah just change the string and -re`gpg --detach-sign` the assert file

**Comment by achow101** [comment]
Resigned

**Pull request merged**
