### PR TITLE
CoinForensics 0.21.1 macOS signed

### PR DESCRIPTION
**Pull request by coinforensics**

### CODE REVIEW

**Comment by Sjors** [comment]
@coinforensics where do I find the PGP public key you're using to sign? It doesn't seem to be on https://keybase.io/coinforensics

**Comment by Sjors** [comment]
Found it: https://github.com/bitcoin/bitcoin/pull/20989

**Comment by coinforensics** [comment]
@Sjors 
It is a dedicated signing key: https://coinforensics.keybase.pub/pgp/signing_key.asc

**Comment by fnsengineering** [comment]
> 

ctos 860925-02-5999 clear off

**Pull request merged**
