### PR TITLE
erkmos 0.11.0rc1 sigs

### PR DESCRIPTION
**Pull request by erkmos**
My signatures for 0.11.0rc1

My key can be found at https://stats.etyd.org/erik.pubkey.txt

### CODE REVIEW

**Comment by theuni** [comment]
No match on our OSX sigs. I deleted the cache and re-ran and got the same results, so I'm guessing it's deterministic but our SDKs differ.

Did your SDK come from xcode_6.1.1.dmg?

**Comment by theuni** [comment]
I'm unsure if yours/mine (or neither) are correct. Leaving this open until we have a 3rd builder to compare against.

**Comment by erkmos** [comment]
Sorry, I must’ve missed that your sigs didn’t match before I submitted (it was kind of late). 

Yes, I’m using the 10.9 SDK from 6.1.1, downloaded yesterday from Apple.

1ad39f89a398d473cfcc5d610b836d240668804818afe58374aa58dcf56a5ccc  xcode_6.1.1.dmg

I’ll try building again later today and see if something changes.

**Comment by jonasschnelli** [comment]
My hashes do match with @erkmos. I didn't touch the MacOSXSDK at all because it was already 10.9 before 0.11.

**Comment by jonasschnelli** [comment]
@erkmos would you mind PRing your key to https://github.com/bitcoin/bitcoin/tree/master/contrib/gitian-downloader.
I try to create a verify app where the sigs get checked agains verified keys on bitcoin.git

**Comment by erkmos** [comment]
@jonasschnelli sure, but my key isn't part of the bitcoin core web of trust. I always thought the keys in bitcoin core git were for keys that had been verified by at least one of the developers?

**Comment by jonasschnelli** [comment]
@erkmos If someone (or an app) likes to verify the signature, it/he will require your gpg pub key. In the gitian git repository we can only find "erkmos" as identifier to your/a identity. Now the question is, how should someone be able to get your key?
Therefore i'd propose that every gitian building participant push his key to the bitcoin git repository. This key then is verified and forged into heavy to tamper and commit signed git repository.

**Comment by erkmos** [comment]
Just tried building again after clearing my cache, can verify that my builds match @jonasschnelli builds but still not @theuni

I'm using precise with lxc 0.7.5 btw, I'll try building on trusty aswell.

@jonasschnelli sure, makes sense. It's why I always include a link to my key, but of course its more convenient to have it in some place everyone knows to look in. I submitted a PR for it

**Comment by theuni** [comment]
Sorry for the late response, I was stuck in an appt. all day.

Yes, it looks like my SDK is the busted one here. I probably messed with it at some point while working on the upgrade. I'll grab a clean one and rebuild.

**Comment by theuni** [comment]
Got a match.

**Pull request merged**
