### PR TITLE
v0.10.1rc1-osx-unsigned : no sigs match, because everyone else seems

### PR DESCRIPTION
**Pull request by midnightmagic**
to be doing KVM builds instead of LXC, and the LXC build is currently
divergent.

### CODE REVIEW

**Comment by Michagogo** [comment]
No, this is still just you having that bizarre divergence. My LXC build matches everyone else.

**Comment by midnightmagic** [comment]
What's your host OS and kernel?

**Comment by Michagogo** [comment]
Ubuntu Desktop 14.04, the latest kernel as of a couple days ago, running in
Virtualbox on Windows 7 Home Premium.

**Comment by midnightmagic** [comment]
I'm on server 12.04.x LTS prior to HWE kernel update due to stability issues on larger hardware.

If I can I'll install another machine and try with 14.04. I am unable to update the machine due to irritating kernel and software dependencies which cannot currently be solved.

**Pull request merged**
